In [1]:
my_list=[1,2,3]

In [ ]:
import numpy as np 
array=np.array(my_list)
print(array)


In [17]:
ar=np.arange(1,21)
print(ar)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [20]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
a=np.zeros((4,3))
a=a.astype(int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [31]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
b=np.ones((4,4))
b=b.astype(int)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [36]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [38]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [40]:
np.random.rand(5)

array([0.12948475, 0.58856958, 0.56005803, 0.35020128, 0.33509675])

In [42]:
np.random.randn(5)

array([ 0.48775911,  0.1897245 , -1.06565229,  0.93518463,  1.77231031])

In [44]:
np.random.randn(4,4)

array([[ 0.81917901, -2.66040258,  1.10144987,  1.05358187],
       [-1.36040495, -0.33438063,  0.47763655, -0.95397025],
       [-0.46547075, -0.00926449, -0.49157348,  0.80300819],
       [-1.27446811,  0.53535581,  1.83599651,  0.59901855]])

In [47]:
np.random.randint(1,100)

98

In [50]:
n=np.random.randint(1,100,10)
print(n)

[ 4 85 32 48 62 18 87 52 33 74]


In [52]:
n.shape

(10,)

In [54]:
n.reshape(5,2)

array([[ 4, 85],
       [32, 48],
       [62, 18],
       [87, 52],
       [33, 74]])

In [62]:
n.reshape(1,10)

array([[ 4, 85, 32, 48, 62, 18, 87, 52, 33, 74]])

In [58]:
n.reshape(10,1)

array([[ 4],
       [85],
       [32],
       [48],
       [62],
       [18],
       [87],
       [52],
       [33],
       [74]])

In [60]:
n.max()

87

In [63]:
n.argmax()

6

In [65]:
n.min()

4

In [67]:
n.argmin()

0

In [69]:
m=np.arange(0,10)

In [71]:
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
m[0:6]

array([0, 1, 2, 3, 4, 5])

In [76]:
m[:3]

array([0, 1, 2])

In [78]:
m[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [80]:
a2=np.array([[32,30,31],[40,41,42],[50,51,52]])

In [82]:
a2

array([[32, 30, 31],
       [40, 41, 42],
       [50, 51, 52]])

In [98]:
a2[2,0]

50

In [100]:
a2[2][0]

50

In [102]:
a2[:2,1:]

array([[30, 31],
       [41, 42]])

In [104]:
a2[:2]

array([[32, 30, 31],
       [40, 41, 42]])

In [107]:
a2

array([[32, 30, 31],
       [40, 41, 42],
       [50, 51, 52]])

In [113]:
a2[1:,:2]

array([[40, 41],
       [50, 51]])

In [116]:
p=np.arange(1,15)
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [118]:
p>8

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True])

In [120]:
bool_p=p>8

In [122]:
p[bool_p]

array([ 9, 10, 11, 12, 13, 14])

In [124]:
p[p>8]

array([ 9, 10, 11, 12, 13, 14])

In [126]:
ab=np.arange(100).reshape(25,4)
ab

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])